### PR TITLE
add test for Node 16

### PR DESCRIPTION
**Pull request by tjulien**
Looks like Node 16 works.

### CODE REVIEW

**Comment by tjulien** [comment]
@jkao Think it's worth pulling in latest commit from the core lib under `third_party/s2geometry`?

```
tim@tjulien s2 % git status
On branch timjulien/ch6736/upgrade-frontend-and-server-to-node-16
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   test.sh
	modified:   third_party/s2geometry (new commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	docker/Dockerfile.node16.test
````

**Comment by jkao** [comment]
The test script is for local runs, you'll also need to modify the `.circleci/config.yml` file for CircleCI

**Comment by jkao** [comment]
we can pull in the latest commits in another PR

**Comment by tjulien** [comment]
Added circle build step for Node 16

**Review by jkao — APPROVED** [review]

**Pull request merged**
